import type { Metadata } from "next";
import {  Lato ,Questrial} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner"
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";




const questrial = Questrial({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: "400",
});

const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${questrial.variable} ${lato.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
        <Toaster theme="dark" richColors />
      </body>
    </html>
  );
}
